//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int SaleID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<byte> Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
